USE [SIC]
GO

CREATE TABLE CONHECIMENTO (
  DOCUMENTO             VARCHAR(20) NOT NULL PRIMARY KEY,
  DT_ATUAL              DATETIME DEFAULT CURRENT_TIMESTAMP,
  COMPROVANTE_ENVIADO   INT DEFAULT 0,
  COMPROVANTE_ORIGEM    VARCHAR(20),
  DT_ENVIO              DATETIME, 
  QTDE_LOAD             INT DEFAULT 0,
  QTDE_SEND             INT DEFAULT 0
);


/* (12/11/2020)
ALTER TABLE CONHECIMENTO ADD  COMPROVANTE_ENVIADO INT DEFAULT 0;
ALTER TABLE CONHECIMENTO ADD  COMPROVANTE_ORIGEM  VARCHAR(20);
ALTER TABLE CONHECIMENTO ADD  DT_ENVIO            DATETIME; 
ALTER TABLE CONHECIMENTO ADD  QTDE_LOAD           INT DEFAULT 0;
ALTER TABLE CONHECIMENTO ADD  QTDE_SEND           INT DEFAULT 0;

UPDATE CONHECIMENTO
SET COMPROVANTE_ENVIADO = 0,QTDE_LOAD = 0,QTDE_SEND = 0 ;
*/