USE [SIC]
GO

CREATE TABLE DE_PARA_OCORRENCIAS (
  ID                INT           NOT NULL    IDENTITY    PRIMARY KEY,
  CNPJ              VARCHAR(14)   NOT NULL,
  CARGAS_ID         INT           NOT NULL,
  CASUAL_ID         INT,
  TRANSPORTE_ID     INT,
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
  OBSERVACAO        VARCHAR(250),
);

GO

CREATE UNIQUE INDEX IDX_DE_PARA_OCORRENCIAS_UK
ON SIC.dbo.DE_PARA_OCORRENCIAS(CNPJ,CARGAS_ID);



--select CNPJ,CARGAS_ID,Count(*) 
--from DE_PARA_OCORRENCIAS
--group by CNPJ,CARGAS_ID
--delete from DE_PARA_OCORRENCIAS where CARGAS_ID in ( 81,16,19 ) and TRANSPORTE_ID=1
