USE [SIC]
GO

CREATE TABLE OCORRENCIAS_CASUAIS (
  ID                INT           NOT NULL    IDENTITY    PRIMARY KEY,
  CNPJ              VARCHAR(14)   NOT NULL,
  CASUAL_ID         INT           NOT NULL,
  DESCRICAO         VARCHAR(80)   NOT NULL,
  LIB_FATURAMENTO   VARCHAR(1)    NOT NULL,
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
);

GO

CREATE UNIQUE INDEX IDX_OCORRENCIAS_CASUAIS_UK
ON SIC.dbo.OCORRENCIAS_CASUAIS(CNPJ,CASUAL_ID);

GO

