USE [SIC]
GO

CREATE TABLE OCORRENCIAS_TRANSPORTE (
  ID                INT           NOT NULL    IDENTITY    PRIMARY KEY,
  CNPJ              VARCHAR(14)   NOT NULL,
  TRANSPORTE_ID     INT           NOT NULL,
  DESCRICAO         VARCHAR(80)   NOT NULL,
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
);

GO

CREATE UNIQUE INDEX IDX_OCORRENCIAS_TRANSPORTE_UK
ON SIC.dbo.OCORRENCIAS_TRANSPORTE(CNPJ,TRANSPORTE_ID);

GO

