-- ( 13/11/2020 )
-- CARGASSQL.dbo.
-- SIC.dbo.
-- CREATE [ OR ALTER ] VIEW

USE [SIC]
GO

ALTER VIEW CONHECIMENTOS_INICIADOS_VW
AS  
 SELECT   
	CNH.%%physloc%%                         as ID,
	CONCAT(CNH.EMP_CODIGO,SERIE,CTRC)       as DOCUMENTO,
    CURRENT_TIMESTAMP                       as DT_ATUAL
FROM CARGASSQL.dbo.CNH
    JOIN CARGASSQL.dbo.CTE               ON CTE.EMP_CODIGO_CNH = CNH.EMP_CODIGO	AND 
	                                        CTE.CNH_SERIE      = CNH.SERIE	AND 
											CTE.CNH_CTRC       = CNH.CTRC											
	JOIN SIC.dbo.CLIENTES CLI            ON CLI.REF_LAYOUT = 1 AND (
	                                        CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_PAG,1,8)  OR 
											CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_DEST,1,8) OR
											CLI.CNPJ_CLI   = SUBSTRING(CNH.CLI_CGCCPF_REMET,1,8) )
	LEFT JOIN SIC.dbo.CONHECIMENTO CON   ON CON.DOCUMENTO  = CONCAT(CNH.EMP_CODIGO,SERIE,CTRC) 	
WHERE CNH.DATATU BETWEEN (CURRENT_TIMESTAMP-7) AND (CURRENT_TIMESTAMP+0) 
AND CTE.PROTOCOLOCTE IS NOT NULL
AND CON.DT_ATUAL IS NULL
;

GO
