SELECT CAST(OCO.DT_ATUAL AS DATE) AS DATA,
       COUNT(OCO.ID) AS TOTAL,
	   SUM(ISNULL(CON.COMPROVANTE_ENVIADO,0)) AS IMAGENS,
	   SUM(CASE WHEN (OCO.RET_SUCESSO=0) AND (OCO.QTD_REENVIO>0) THEN 1 ELSE 0 END) ERROS,
	   SUM(OCO.QTD_REENVIO) AS REENVIOS,
	   SUM(OCO.RET_SUCESSO) AS SUCESSO,
	   (COUNT(OCO.ID)-SUM(OCO.RET_SUCESSO)) AS PENDENTES
FROM OCORRENCIAS  OCO
LEFT JOIN CONHECIMENTO CON ON CON.DOCUMENTO = OCO.DOCUMENTO AND 
          CAST(CON.DT_ATUAL AS DATE) = CAST(OCO.DT_ATUAL AS DATE)
GROUP BY CAST(OCO.DT_ATUAL AS DATE)
ORDER BY CAST(OCO.DT_ATUAL AS DATE)