SELECT D.CARGAS_ID,D.OBSERVACAO,D.CASUAL_ID,C.DESCRICAO AS CASUAL,C.LIB_FATURAMENTO,D.TRANSPORTE_ID,T.DESCRICAO AS TRANSPORTE 
FROM DE_PARA_OCORRENCIAS    AS D
JOIN OCORRENCIAS_CASUAIS    AS C ON C.CASUAL_ID     = D.CASUAL_ID     AND C.CNPJ = D.CNPJ
JOIN OCORRENCIAS_TRANSPORTE AS T ON T.TRANSPORTE_ID = D.TRANSPORTE_ID AND C.CNPJ = D.CNPJ
WHERE D.CNPJ = '${cnpj}'
ORDER BY D.CARGAS_ID
