UPDATE SIC.dbo.OCORRENCIAS
SET RET_MENSAGEM  = NULL,
    RET_PROTOCOLO = NULL,
    RET_SUCESSO   = NULL,
    DT_ENVIO      = NULL,
	QTD_REENVIO   = QTD_REENVIO + 1
  WHERE 
    RET_SUCESSO = 0 AND QTD_REENVIO < 5 AND RET_MENSAGEM IS NOT NULL AND
    DATEDIFF(minute,DT_ATUAL, CURRENT_TIMESTAMP) > 30
;