INSERT INTO SIC.dbo.OCORRENCIAS (
	DOCUMENTO,CHAVE,CHAVEORIGINAL,CNPJ,
	DT_ATUAL,DT_OCORRENCIA,DT_SOLUCAO,REPLICAR,  
	OBSERVACAO,OCORR301,OCORR302,OCORRCASUAL,
	OCORRTRANSPORTE,OCORRSIMPLIFICADA,URL_ENDPOINT,RET_SUCESSO, 
	OUN_TABELA,OUN_CHAVE,OUN_DATE,OUN_CODIGO )
SELECT
	cast(DOCUMENTO as varchar(20)),CHAVE,CHAVEORIGINAL,CNPJ,
	DT_ATUAL,DT_OCORRENCIA,DT_SOLUCAO,REPLICAR,  
	cast(OBSERVACAO as varchar(250)),OCORR301,OCORR302,OCORRCASUAL,
	OCORRTRANSPORTE, OCORRSIMPLIFICADA,	URL_ENDPOINT,RET_SUCESSO, 
	OUN_TABELA,cast(OUN_CHAVE as varchar(20)),CURRENT_TIMESTAMP,OUN_CODIGO 
FROM
	OCORRENCIAS_BAIXAS_VW